spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:tasks;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    username: dk
    password: qwerty
  h2:
    console:
      enable: true