spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=PostgreSQL;
    username: dk
    password: qwerty
  jpa:
    database-platform: org.hibernate.dialect.H2Dialectue
  h2:
    console:
      enable: true
      path: /h2-console/
      settings.trace: false
      settings.web-allow-others: false