spring:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create

  output:
    ansi:
      enabled: always
  instancio:
    bean:
      validation:
        enabled: true
  sql:
    init:
      mode: always
  profiles:
    default: dev

logging:
  level:
    root: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    pretty-print: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem